# Generated by Django 4.0.2 on 2022-05-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stu_work',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
