# Generated by Django 4.0.2 on 2022-05-10 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_stu_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stu_work',
        ),
    ]
