# Generated by Django 4.0.2 on 2022-05-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_user_stu_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.CharField(default='NO', max_length=3),
        ),
    ]
